version: '3.8'

services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "8080:8080" # NiFi web UI
    volumes:
      - ./datalake:/opt/nifi/nifi-current/datalake # Mount local directory to NiFi
    environment:
      - NIFI_WEB_HTTP_PORT=8080

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432" # PostgreSQL port
    environment:
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_DB=superset
    volumes:
      - postgres-data:/var/lib/postgresql/data

  superset:
    image: apache/superset:latest
    depends_on:
      - postgres
    ports:
      - "8088:8088" # Superset web UI
    environment:
      - SUPERSET_DB_USER=superset
      - SUPERSET_DB_PASS=superset
      - SUPERSET_DB_NAME=superset
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
    volumes:
      - superset-data:/app/superset_home

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  superset-data:
